version: "3.3"
services:
  core:
    image: alaskanpuffin/herodotus-core:latest
    volumes:
      - "herodotus:/app/data"
    networks:
      - herodotus-network
    links:
      - meilisearch
    depends_on:
      - meilisearch
    ports:
      - "8080:8080"
    environment:
      - MEILI_SEARCH_URL=http://meilisearch:7700
      - MEILI_SEARCH_MASTER_KEY=<MEILI_MASTER_KEY>
      - SECRET_KEY=<SECRET_KEY>
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.pullfeeds.schedule: "@every 1h" # Frequency the feeds are pulled for new articles
      ofelia.job-exec.pullfeeds.command: "python /app/manage.py pull_feeds"

  web:
    image: alaskanpuffin/herodotus-web:latest
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_ROOT=http://<HERODOTUS-CORE-IP/HOSTNAME>:8080 # Do not include a trailing slash

  meilisearch:
    image: getmeili/meilisearch:latest
    networks:
      - herodotus-network
    volumes:
      - meilisearch:/data.ms
    expose:
      - "7700"
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=<MEILI_MASTER_KEY>

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - core
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  herodotus:

networks:
  herodotus-network:
  meilisearch: