# Generated by Django 3.1 on 2020-09-07 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
