# Generated by Django 3.1 on 2020-09-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0003_auto_20200907_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='richtext',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('note', 'note'), ('article', 'article')], max_length=30),
        ),
    ]
