# Generated by Django 3.1 on 2020-09-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0005_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='publisher',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
