# Generated by Django 3.1 on 2020-09-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0006_content_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herodotus.feed')),
            ],
        ),
    ]
