# Generated by Django 3.1 on 2020-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0008_auto_20201005_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
