# Generated by Django 3.1 on 2020-10-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0010_auto_20201005_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('article', 'article'), ('note', 'note')], max_length=30),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='herodotus.Tag'),
        ),
    ]
