# Generated by Django 3.1 on 2020-11-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herodotus', '0013_auto_20201031_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(blank=True, to='herodotus.Tag'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('note', 'note'), ('article', 'article')], max_length=30),
        ),
    ]
